no error after context creation with attributes
