no error after destroying context
