no error after context creation
